/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BingoSqlImport } from './routes/bingo-sql'
import { Route as BingoImport } from './routes/bingo'
import { Route as Advent2024Import } from './routes/advent2024'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BingoSqlRoute = BingoSqlImport.update({
  id: '/bingo-sql',
  path: '/bingo-sql',
  getParentRoute: () => rootRoute,
} as any)

const BingoRoute = BingoImport.update({
  id: '/bingo',
  path: '/bingo',
  getParentRoute: () => rootRoute,
} as any)

const Advent2024Route = Advent2024Import.update({
  id: '/advent2024',
  path: '/advent2024',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/advent2024': {
      id: '/advent2024'
      path: '/advent2024'
      fullPath: '/advent2024'
      preLoaderRoute: typeof Advent2024Import
      parentRoute: typeof rootRoute
    }
    '/bingo': {
      id: '/bingo'
      path: '/bingo'
      fullPath: '/bingo'
      preLoaderRoute: typeof BingoImport
      parentRoute: typeof rootRoute
    }
    '/bingo-sql': {
      id: '/bingo-sql'
      path: '/bingo-sql'
      fullPath: '/bingo-sql'
      preLoaderRoute: typeof BingoSqlImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advent2024': typeof Advent2024Route
  '/bingo': typeof BingoRoute
  '/bingo-sql': typeof BingoSqlRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advent2024': typeof Advent2024Route
  '/bingo': typeof BingoRoute
  '/bingo-sql': typeof BingoSqlRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/advent2024': typeof Advent2024Route
  '/bingo': typeof BingoRoute
  '/bingo-sql': typeof BingoSqlRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advent2024' | '/bingo' | '/bingo-sql'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advent2024' | '/bingo' | '/bingo-sql'
  id: '__root__' | '/' | '/advent2024' | '/bingo' | '/bingo-sql'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Advent2024Route: typeof Advent2024Route
  BingoRoute: typeof BingoRoute
  BingoSqlRoute: typeof BingoSqlRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Advent2024Route: Advent2024Route,
  BingoRoute: BingoRoute,
  BingoSqlRoute: BingoSqlRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/advent2024",
        "/bingo",
        "/bingo-sql"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/advent2024": {
      "filePath": "advent2024.tsx"
    },
    "/bingo": {
      "filePath": "bingo.tsx"
    },
    "/bingo-sql": {
      "filePath": "bingo-sql.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
