/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const BingoSqlLazyImport = createFileRoute('/bingo-sql')()
const BingoLazyImport = createFileRoute('/bingo')()
const Advent2024LazyImport = createFileRoute('/advent2024')()

// Create/Update Routes

const BingoSqlLazyRoute = BingoSqlLazyImport.update({
  id: '/bingo-sql',
  path: '/bingo-sql',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bingo-sql.lazy').then((d) => d.Route))

const BingoLazyRoute = BingoLazyImport.update({
  id: '/bingo',
  path: '/bingo',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bingo.lazy').then((d) => d.Route))

const Advent2024LazyRoute = Advent2024LazyImport.update({
  id: '/advent2024',
  path: '/advent2024',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/advent2024.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/advent2024': {
      id: '/advent2024'
      path: '/advent2024'
      fullPath: '/advent2024'
      preLoaderRoute: typeof Advent2024LazyImport
      parentRoute: typeof rootRoute
    }
    '/bingo': {
      id: '/bingo'
      path: '/bingo'
      fullPath: '/bingo'
      preLoaderRoute: typeof BingoLazyImport
      parentRoute: typeof rootRoute
    }
    '/bingo-sql': {
      id: '/bingo-sql'
      path: '/bingo-sql'
      fullPath: '/bingo-sql'
      preLoaderRoute: typeof BingoSqlLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advent2024': typeof Advent2024LazyRoute
  '/bingo': typeof BingoLazyRoute
  '/bingo-sql': typeof BingoSqlLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advent2024': typeof Advent2024LazyRoute
  '/bingo': typeof BingoLazyRoute
  '/bingo-sql': typeof BingoSqlLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/advent2024': typeof Advent2024LazyRoute
  '/bingo': typeof BingoLazyRoute
  '/bingo-sql': typeof BingoSqlLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advent2024' | '/bingo' | '/bingo-sql'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advent2024' | '/bingo' | '/bingo-sql'
  id: '__root__' | '/' | '/advent2024' | '/bingo' | '/bingo-sql'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Advent2024LazyRoute: typeof Advent2024LazyRoute
  BingoLazyRoute: typeof BingoLazyRoute
  BingoSqlLazyRoute: typeof BingoSqlLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Advent2024LazyRoute: Advent2024LazyRoute,
  BingoLazyRoute: BingoLazyRoute,
  BingoSqlLazyRoute: BingoSqlLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/advent2024",
        "/bingo",
        "/bingo-sql"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/advent2024": {
      "filePath": "advent2024.lazy.tsx"
    },
    "/bingo": {
      "filePath": "bingo.lazy.tsx"
    },
    "/bingo-sql": {
      "filePath": "bingo-sql.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
